spring.config.import=optional:file:.env[.properties]
spring.application.name=resources
spring.profiles.active=dev
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:resources}?createDatabaseIfNotExists=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.jpa.properties.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}
anthropic.api.key=${ANTHROPIC_API_KEY:}

